name: Build
on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        addrsize: ["64"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Homebrew Packages
        if: ${{ runner.os == 'macOS' }}
        shell: bash
        run: brew install ninja
      - uses: secondlife/action-autobuild@v4
        with:
          addrsize: ${{ matrix.addrsize }}
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v3